=== CrazyBunQnQ/KeyManager/WebContent/users.dtd
<!ELEMENT users (user*)>
<!ELEMENT user (uname,upwd,age,sex)>
<!ELEMENT uname (#PCDATA)>
<!ELEMENT upwd (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ATTLIST user 
	id ID #REQUIRED
	height CDATA #IMPLIED
>

=== CrazyBunQnQ/KeyManager/WebContent/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE users SYSTEM "users.dtd">
<users>
	<user id="u1" height="180">
		<uname>bao</uname>
		<upwd>123456</upwd>
		<age>18</age>
		<sex>M</sex>
	</user>
	<user id="u2">
		<uname>hao</uname>
		<upwd>123</upwd>
		<age>16</age>
		<sex>F</sex>
	</user>
</users>
